# Generated by Django 3.1.1 on 2020-11-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='image_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Uploaded Image'),
        ),
    ]
